// African countries. `value` is the lowercase name stored in the DB, matching
// the existing `tanzania` / `rwanda` convention.
export const AFRICAN_COUNTRIES = [
  // Priority markets first, then the rest alphabetically.
  { value: 'tanzania', label: 'Tanzania', flag: '🇹🇿' },
  { value: 'rwanda', label: 'Rwanda', flag: '🇷🇼' },
  { value: 'kenya', label: 'Kenya', flag: '🇰🇪' },
  { value: 'botswana', label: 'Botswana', flag: '🇧🇼' },
  { value: 'uganda', label: 'Uganda', flag: '🇺🇬' },
  { value: 'algeria', label: 'Algeria', flag: '🇩🇿' },
  { value: 'angola', label: 'Angola', flag: '🇦🇴' },
  { value: 'benin', label: 'Benin', flag: '🇧🇯' },
  { value: 'burkina faso', label: 'Burkina Faso', flag: '🇧🇫' },
  { value: 'burundi', label: 'Burundi', flag: '🇧🇮' },
  { value: 'cabo verde', label: 'Cabo Verde', flag: '🇨🇻' },
  { value: 'cameroon', label: 'Cameroon', flag: '🇨🇲' },
  { value: 'central african republic', label: 'Central African Republic', flag: '🇨🇫' },
  { value: 'chad', label: 'Chad', flag: '🇹🇩' },
  { value: 'comoros', label: 'Comoros', flag: '🇰🇲' },
  { value: 'congo', label: 'Congo (Republic)', flag: '🇨🇬' },
  { value: 'dr congo', label: 'DR Congo', flag: '🇨🇩' },
  { value: "cote d'ivoire", label: "Côte d'Ivoire", flag: '🇨🇮' },
  { value: 'djibouti', label: 'Djibouti', flag: '🇩🇯' },
  { value: 'egypt', label: 'Egypt', flag: '🇪🇬' },
  { value: 'equatorial guinea', label: 'Equatorial Guinea', flag: '🇬🇶' },
  { value: 'eritrea', label: 'Eritrea', flag: '🇪🇷' },
  { value: 'eswatini', label: 'Eswatini', flag: '🇸🇿' },
  { value: 'ethiopia', label: 'Ethiopia', flag: '🇪🇹' },
  { value: 'gabon', label: 'Gabon', flag: '🇬🇦' },
  { value: 'gambia', label: 'Gambia', flag: '🇬🇲' },
  { value: 'ghana', label: 'Ghana', flag: '🇬🇭' },
  { value: 'guinea', label: 'Guinea', flag: '🇬🇳' },
  { value: 'guinea-bissau', label: 'Guinea-Bissau', flag: '🇬🇼' },
  { value: 'lesotho', label: 'Lesotho', flag: '🇱🇸' },
  { value: 'liberia', label: 'Liberia', flag: '🇱🇷' },
  { value: 'libya', label: 'Libya', flag: '🇱🇾' },
  { value: 'madagascar', label: 'Madagascar', flag: '🇲🇬' },
  { value: 'malawi', label: 'Malawi', flag: '🇲🇼' },
  { value: 'mali', label: 'Mali', flag: '🇲🇱' },
  { value: 'mauritania', label: 'Mauritania', flag: '🇲🇷' },
  { value: 'mauritius', label: 'Mauritius', flag: '🇲🇺' },
  { value: 'morocco', label: 'Morocco', flag: '🇲🇦' },
  { value: 'mozambique', label: 'Mozambique', flag: '🇲🇿' },
  { value: 'namibia', label: 'Namibia', flag: '🇳🇦' },
  { value: 'niger', label: 'Niger', flag: '🇳🇪' },
  { value: 'nigeria', label: 'Nigeria', flag: '🇳🇬' },
  { value: 'sao tome and principe', label: 'São Tomé and Príncipe', flag: '🇸🇹' },
  { value: 'senegal', label: 'Senegal', flag: '🇸🇳' },
  { value: 'seychelles', label: 'Seychelles', flag: '🇸🇨' },
  { value: 'sierra leone', label: 'Sierra Leone', flag: '🇸🇱' },
  { value: 'somalia', label: 'Somalia', flag: '🇸🇴' },
  { value: 'south africa', label: 'South Africa', flag: '🇿🇦' },
  { value: 'south sudan', label: 'South Sudan', flag: '🇸🇸' },
  { value: 'sudan', label: 'Sudan', flag: '🇸🇩' },
  { value: 'togo', label: 'Togo', flag: '🇹🇬' },
  { value: 'tunisia', label: 'Tunisia', flag: '🇹🇳' },
  { value: 'zambia', label: 'Zambia', flag: '🇿🇲' },
  { value: 'zimbabwe', label: 'Zimbabwe', flag: '🇿🇼' },
] as const;
